name: ci-build
on:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ndk
        run: |
          ndk_url=$(wget -qO- https://github.com/android/ndk/releases/latest | grep -e 'https://dl.google.com/android/repository/android-ndk-.*-linux.zip' | sed -n 's/.*<a href="\([^"]*\)".*/\1/p')
          wget -O ndk.zip $ndk_url -nv
          mkdir -p ~/ndk_temp
          unzip ndk.zip -d ~/ndk_temp 2>&1 > /dev/null
          mv ~/ndk_temp/*/* ~/ndk_temp
      - name: Setup rust toolchains
        run: |
          rustup default nightly
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
          rustup component add rust-src
          rustup update
      - name: Install cargo ndk
        run: cargo install cargo-ndk
      - name: Other deps
        run: |
          sudo apt update
          sudo apt install gcc-multilib upx -y
      - name: Build
        run: |
          export ANDROID_NDK_HOME=$(realpath ~/ndk_temp)
          export ANDROID_NDK_ROOT=$ANDROID_NDK_HOME
          git clone https://github.com/Tools-cx-app/life-death-scheduler-release.git module
          cargo ndk -t arm64-v8a build -r
          upx --lzma target/aarch64-linux-android/release/life-death-scheduler
          cp target/aarch64-linux-android/release/life-death-scheduler module/
          zip -r life-death-scheduler.zip module
          rm ~/ndk_temp -rf
      - name: Upload
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          COMMIT_MESSAGE: |+
            New push to GitHub
            ```
            ${{ github.event.head_commit.message }}
            ```by `${{ github.event.head_commit.author.name }}`
        run: |
          VERISON=$(git rev-list  --all --count)
          MSG="${COMMIT_MESSAGE}\n${VERISON}"
          ESCAPED=$(python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))')
          # 上传文件
          curl -v "https%3a%2f%2fapi.telegram.org%2fbot%24%7bBOT_TOKEN%7d%2fsendMediaGroup%3fchat_id%3d%24%7bCHAT_ID%7d%26message_thread_id%3d5%26media%3d%5b%7b%22type%22%3a%22document%22%2c%22media%22%3a%22attach%3a%2f%2ffile%22%2c%22parse_mode%22%3a%22MarkdownV2%22%2c%22caption%22%3a%24%7bESCAPED%7d%7d%5d" -F file=@"life-death-scheduler.zip"
